// <auto-generated />
namespace MachineryProcessingDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addQualityData_OnlineType1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addQualityData_OnlineType1));
        
        string IMigrationMetadata.Id
        {
            get { return "202103200931223_addQualityData_OnlineType1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
