// <auto-generated />
namespace MachineryProcessingDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addQualityData_OnlineType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addQualityData_OnlineType));
        
        string IMigrationMetadata.Id
        {
            get { return "202103200926210_addQualityData_OnlineType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
